/**
 * Mã lỗi backend → câu tiếng Việt cho trang quản trị（纯函数，无 @/ 依赖，供 node --test 直接导入）。
 * 键与 backend/app/errors.py 的 ERRORS 一致（tests/test_app_errors.py 校验）；文案同用户端 frontend/src/i18n/locales/vi/errors.ts。
 */
export const ADMIN_ERROR_MESSAGES: Record<string, string> = {
  'common.unsupported_image_type': 'Chỉ hỗ trợ ảnh JPG, PNG, WebP hoặc GIF',
  'common.empty_file': 'File trống, vui lòng chọn file khác',
  'common.file_too_large': 'File không được vượt quá {max_mb} MB',
  'common.invalid_image': 'File này không phải ảnh hợp lệ',
  'common.user_not_found': 'Không tìm thấy tài khoản',
  'auth.email_registered': 'Email này đã được đăng ký',
  'auth.invalid_credentials': 'Email hoặc mật khẩu không đúng',
  'auth.wrong_current_password': 'Mật khẩu hiện tại không đúng',
  'auth.same_password': 'Mật khẩu mới phải khác mật khẩu hiện tại',
  'auth.email_taken': 'Email này đã có người sử dụng',
  'auth.service_unavailable': 'Hệ thống đang bận, vui lòng thử lại sau',
  'auth.reset_token_invalid': 'Link đặt lại mật khẩu không hợp lệ hoặc đã hết hạn',
  'auth.username_required': 'Vui lòng nhập tên người dùng',
  'auth.username_too_long': 'Tên người dùng tối đa {max} ký tự',
  'auth.email_invalid': 'Email không đúng định dạng',
  'auth.phone_invalid': 'Số điện thoại không đúng định dạng',
  'model.slot_not_configured': 'Chức năng này chưa được cấu hình mô hình, hãy liên hệ với chúng tôi',
  'model.not_available': 'Mô hình đã chọn hiện không khả dụng, vui lòng chọn lại',
  'billing.insufficient_balance': 'Số dư không đủ: cần {need}, hiện có {available}. Vui lòng nạp thêm tiền',
  'billing.insufficient_balance_pending': 'Số dư không đủ: lần này cần {need} (tính cả {pending} đang chờ), hiện có {available}. Vui lòng nạp thêm tiền',
  'billing.insufficient_balance_batch': 'Số dư không đủ: tạo {qty} mục cần {need} (tính cả {pending} đang chờ), hiện có {available}. Vui lòng nạp thêm tiền',
  'billing.unknown_package': 'Gói nạp không tồn tại',
  'billing.topup_unavailable': 'Chưa mở nạp tiền: hệ thống chưa cấu hình tài khoản nhận tiền',
  'billing.alert_not_found': 'Không tìm thấy cảnh báo',
  'billing.order_not_found': 'Không tìm thấy đơn nạp tiền',
  'billing.order_paid_cannot_close': 'Đơn đã thanh toán, không thể huỷ',
  'billing.order_cannot_close': 'Không thể huỷ đơn ở trạng thái này',
  'billing.order_closed': 'Đơn đã huỷ nên không thể cộng tiền vào số dư',
  'task.not_found': 'Không tìm thấy yêu cầu này',
  'task.mock_limit': 'Chỉ chạy tối đa {max} lượt thử cùng lúc',
  'task.type_not_supported': 'Chức năng này chưa được hỗ trợ',
  'task.target_not_found': 'Không tìm thấy nội dung, hoặc bạn không có quyền truy cập',
  'task.target_mismatch': 'Dữ liệu không khớp, vui lòng tải lại trang',
  'task.invalid_payload': 'Tham số không hợp lệ: {field}',
  'task.payload_out_of_range': 'Tham số {field} phải nằm trong khoảng {min}–{max}',
  'task.cancel_not_supported': 'Không thể huỷ mục này',
  'task.already_finished': 'Đã chạy xong, không thể huỷ',
  'tool.unknown': 'Công cụ không tồn tại',
  'tool.missing_task': 'Thiếu mã yêu cầu',
  'tool.run_not_found': 'Không tìm thấy lượt tạo này',
  'tool.unsupported_file_type': 'Chỉ hỗ trợ file png, jpg, webp, gif, mp4, mov hoặc webm',
  'tool.prompt_required': 'Vui lòng nhập prompt',
  'tool.reference_required': 'Vui lòng tải lên ảnh tham chiếu',
  'tool.product_image_required': 'Vui lòng tải lên ảnh sản phẩm',
  'tool.stitch_min_images': 'Cần tải lên ít nhất {min} ảnh để ghép',
  'tool.video_script_required': 'Vui lòng nhập kịch bản video',
  'tool.video_source_required': 'Vui lòng tải lên video gốc hoặc ảnh khung hình đầu',
  'tool.first_frame_extract_failed': 'Không lấy được khung hình đầu từ video',
  'tool.first_frame_required': 'Thiếu ảnh khung hình đầu, không thể tạo video',
  'tool.run_failed': 'Không tạo được, vui lòng thử lại sau',
  'api_key.not_found': 'API key không tồn tại hoặc đã bị thu hồi',
  'template.not_found': 'Không tìm thấy mẫu',
  'project.not_found': 'Không tìm thấy dự án',
  'project.invalid_template': 'Mẫu không hợp lệ',
  'project.topic_required': 'Vui lòng nhập chủ đề',
  'project.ai_generate_failed': 'AI chưa tạo được nội dung, vui lòng thử lại',
  'project.voice_preview_failed': 'Không tạo được bản nghe thử, vui lòng thử lại',
  'project.full_generation_running': 'Video đang được tạo, vui lòng đợi',
  'project.generation_running': 'Đang tạo, vui lòng đợi',
  'project.locked_while_generating': 'Đang tạo, chưa thể chỉnh sửa',
  'project.cover_locked': 'Đang tạo, chưa thể đổi ảnh bìa',
  'project.download_selection_required': 'Vui lòng chọn video cần tải',
  'project.download_limit': 'Mỗi lần tải tối đa {max} video',
  'project.no_downloadable_video': 'Các video đã chọn chưa có video hoàn chỉnh để tải',
  'project.invalid_cover_url': 'Link ảnh bìa không hợp lệ',
  'project.invalid_image_model': 'Mô hình tạo ảnh không hợp lệ',
  'project.invalid_video_model': 'Mô hình tạo video không hợp lệ',
  'project.ready_to_compose': 'Đã đủ tư liệu, hãy bấm dựng video',
  'project.cannot_cancel': 'Không thể huỷ ở trạng thái hiện tại',
  'project.shot_list_incomplete': 'Danh sách cảnh chưa đầy đủ',
  'project.shot_not_found': 'Không tìm thấy cảnh',
  'project.image_text_no_video': 'Video ảnh tĩnh không cần tạo video AI, hãy dựng lại video',
  'project.shot_image_required': 'Vui lòng tạo hình ảnh cho cảnh này trước',
  'project.no_shots': 'Chưa có phân cảnh, vui lòng tạo trước',
  'project.compose_missing_media': 'Thiếu ảnh hoặc video của cảnh, chưa thể dựng video',
  'project.not_ready_to_publish': 'Video chưa hoàn chỉnh, chưa thể đăng',
  'project.narration_empty': 'Tất cả cảnh đều chưa có lời dẫn, chưa thể tạo giọng đọc',
  'project.shot_narration_empty': 'Chưa có lời dẫn, chưa thể tạo giọng đọc',
  'drama.project_not_found': 'Không tìm thấy phim ngắn',
  'drama.script_not_found': 'Không tìm thấy kịch bản',
  'drama.script_missing': 'Dự án chưa có kịch bản',
  'drama.summary_required': 'Vui lòng tạo tóm tắt kịch bản trước',
  'drama.episode_scripts_required': 'Vui lòng tạo kịch bản các tập trước',
  'drama.creative_too_short': 'Ý tưởng câu chuyện cần ít nhất {min} ký tự',
  'drama.invalid_generate_mode': 'Cách tạo không hợp lệ',
  'drama.episodes_generating': 'Đang viết kịch bản cho tất cả các tập, vui lòng đợi xong rồi hãy chỉnh tập này',
  'drama.episodes_generating_add': 'Đang viết kịch bản cho tất cả các tập, vui lòng đợi xong rồi hãy thêm tập',
  'drama.draft_required': 'Vui lòng nhập bản nháp kịch bản của tập này trước khi nhờ AI chỉnh',
  'drama.draft_too_short': 'Bản nháp kịch bản cần ít nhất {min} ký tự',
  'drama.episode_creative_required': 'Vui lòng nhập ý tưởng của tập này trước (ít nhất {min} ký tự)',
  'drama.episode_body_required': 'Tập này cần có nội dung kịch bản trước, AI mới bổ sung được ý tưởng và tóm tắt',
  'drama.max_episodes': 'Tối đa {max} tập',
  'drama.llm_unavailable': 'Mô hình tạo văn bản đang tạm ngưng, vui lòng thử lại sau',
  'drama.episode_not_found': 'Không tìm thấy tập phim',
  'drama.invalid_episode_number': 'Số tập không hợp lệ',
  'drama.episode_script_not_found': 'Không tìm thấy kịch bản tập {number}',
  'drama.episode_body_too_short': 'Tập {number} quá ngắn, hãy viết xong hoặc nhờ AI chỉnh rồi mới xác nhận làm phân cảnh',
  'drama.invalid_episode_target': 'Thời lượng mong muốn không hợp lệ, hãy chọn Tự động, 30 giây, 60 giây, 90 giây, 2 phút hoặc 3 phút',
  'drama.episode_reload_failed': 'Đã lưu tập phim nhưng chưa tải lại được, vui lòng tải lại trang',
  'drama.asset_not_found': 'Không tìm thấy tư liệu',
  'drama.character_asset_not_found': 'Không tìm thấy nhân vật',
  'drama.character_asset_only': 'Chỉ áp dụng cho tư liệu nhân vật',
  'drama.appearance_extract_failed': 'Không tách được các trường ngoại hình, vui lòng thử lại',
  'drama.prompt_required': 'Vui lòng nhập prompt',
  'drama.voice_prompt_required': 'Vui lòng mô tả giọng',
  'drama.voice_generate_failed': 'Không tạo được giọng, vui lòng thử lại sau',
  'drama.upload_unavailable': 'Chưa hỗ trợ tải ảnh lên, vui lòng liên hệ chúng tôi để bật lưu trữ',
  'drama.upload_read_failed': 'Không đọc được file tải lên',
  'drama.upload_failed': 'Không tải lên được, vui lòng thử lại sau',
  'drama.asset_generating': 'Ảnh đang được tạo, vui lòng đợi xong rồi hãy đổi ảnh',
  'drama.asset_generating_version': 'Ảnh đang được tạo, chưa thể đổi sang phiên bản cũ',
  'drama.no_history_version': 'Chưa có phiên bản cũ nào để đổi',
  'drama.version_not_found': 'Phiên bản này không còn nữa',
  'drama.assets_extracting': 'Đang lấy tư liệu từ kịch bản, vui lòng xác nhận lại sau ít phút',
  'drama.asset_extract_failed': 'Không lấy được tư liệu từ kịch bản, vui lòng thử lại sau',
  'drama.fragment_not_found': 'Không tìm thấy phân cảnh',
  'drama.fragments_protected': 'Tập này có video đã tạo hoặc phân cảnh đã sửa tay, hãy xác nhận nếu muốn chia lại phân cảnh',
  'drama.fragment_generating': 'Phân cảnh đang được tạo, vui lòng đợi xong rồi hãy đổi phiên bản',
  'drama.no_fragments_to_generate': 'Không có phân cảnh nào để tạo (phân cảnh vừa thay đổi sau khi lưu, hãy bấm tạo lại)',
  'drama.fragments_all_generating': 'Các phân cảnh đã chọn đang được tạo, vui lòng đợi',
  'drama.prev_fragment_required': 'Đang bật nối khung hình cuối: hãy tạo cảnh trước và đợi có khung hình cuối rồi mới tạo cảnh này',
  'drama.compose_no_videos': 'Tập này chưa có video phân cảnh nào để ghép',
  'drama.compose_clip_download_failed': 'Không tải được video phân cảnh, vui lòng thử lại sau',
  'drama.compose_failed': 'Không dựng được tập phim, vui lòng thử lại sau',
  'drama.dub_no_video': 'Phân cảnh này chưa có video nên chưa thể lồng tiếng',
  'drama.dub_not_enabled': 'Video phân cảnh này không được tạo ở chế độ lồng tiếng. Hãy bật "Lồng tiếng TTS" trong cài đặt dự án rồi tạo lại video',
  'drama.dub_failed': 'Lồng tiếng thất bại, vui lòng thử lại sau',
  'drama.dub_fragment_generating': 'Phân cảnh đang tạo video hoặc đang lồng tiếng, vui lòng đợi xong rồi thử lại',
  'drama.skill_not_found': 'Không tìm thấy Skill',
  'drama.skill_md_only': 'Vui lòng tải lên file .md',
  'drama.skill_file_too_large': 'File không được vượt quá {max_kb} KB',
  'drama.skill_not_text': 'File phải là văn bản UTF-8',
  'drama.skill_edit_forbidden': 'Không thể sửa Skill của người khác',
  'drama.skill_delete_forbidden': 'Không thể xoá Skill của người khác',
  'drama.skill_builtin_undeletable': 'Không thể xoá Skill có sẵn, bạn có thể tắt nó',
  'drama.skill_builtin_readonly': 'Không thể sửa nội dung Skill có sẵn',
  'drama.skill_empty': 'Skill đang trống',
  'drama.skill_invalid_name': 'Tên Skill chỉ gồm chữ thường, số và dấu gạch ngang',
  'drama.skill_body_empty': 'Nội dung Skill không được để trống',
  'drama.skill_too_long': 'Skill tối đa {max} ký tự',
  'drama.skill_limit': 'Bạn chỉ tải lên được tối đa {max} Skill tự tạo',
  'drama.skill_duplicate': 'Đã có Skill trùng tên, hãy đổi tên hoặc xoá Skill cũ trước',
  // --- Phim ngắn: lỗi việc chạy nền lưu kèm mã (Đợt 2B) ---
  'drama.upstream_auth': 'Nhà cung cấp mô hình từ chối API key, hãy liên hệ với chúng tôi',
  'drama.upstream_rate_limit': 'Nhà cung cấp mô hình đang quá tải, vui lòng thử lại sau',
  'drama.upstream_server': 'Nhà cung cấp mô hình đang gặp sự cố, vui lòng thử lại sau',
  'drama.upstream_rejected': 'Nhà cung cấp mô hình từ chối yêu cầu, vui lòng thử lại sau',
  'drama.upstream_network': 'Không kết nối được nhà cung cấp mô hình, vui lòng thử lại sau',
  'drama.llm_empty_output': 'AI chưa trả về nội dung nào, vui lòng thử lại',
  'drama.llm_bad_format': 'AI trả về kết quả không đọc được, vui lòng thử lại',
  'drama.llm_output_too_short': 'AI viết quá ngắn, vui lòng thử lại',
  'drama.episode_gen_incomplete': 'Mới viết xong {done}/{total} tập, vui lòng thử lại',
  'drama.episode_gen_stalled': 'Việc viết kịch bản các tập bị đứng lại, vui lòng thử lại sau',
  'drama.episode_input_required': 'Vui lòng nhập ý tưởng hoặc tóm tắt của tập này trước',
  'drama.episode_body_empty': 'Kịch bản tập này đang trống nên chưa chia phân cảnh được',
  'drama.visual_prompt_too_short': 'Prompt AI của “{name}” quá ngắn ({length} ký tự), vui lòng thử lại',
  'drama.visual_prompt_failed': 'Không viết được prompt AI cho “{name}”, vui lòng thử lại',
  'drama.gen_failed': 'Không tạo được, vui lòng thử lại sau',
  'drama.gen_timeout': 'Tạo quá lâu nên đã dừng, vui lòng thử lại sau',
  'drama.gen_network': 'Không kết nối được dịch vụ tạo ảnh/video, vui lòng thử lại sau',
  'drama.gen_no_image_url': 'Đã tạo xong nhưng không nhận được ảnh dùng được, vui lòng thử lại',
  'drama.gen_cancelled': 'Đã huỷ tạo',
  'drama.gen_skipped_done': 'Phân cảnh này đã có video nên bỏ qua lần tạo trùng',
  'drama.prev_shot_failed': 'Cảnh trước bị lỗi nên cảnh này không nối được khung hình cuối',
  'drama.fragment_changed': 'Phân cảnh đã thay đổi, vui lòng tạo lại',
  'drama.video_channel_gone': 'Kênh video cũ không còn, hãy tạo lại phân cảnh này',
  'task.missing_provider_task': 'Thiếu mã việc tạo của nhà cung cấp nên không theo dõi được tiến độ',
  'task.video_poll_timeout': 'Video tạo quá lâu nên đã dừng, số tiền tạm giữ đã được hoàn lại',
  'task.upstream_failed': 'Không tạo được, vui lòng thử lại sau',
  // --- Video ngắn / công cụ / tác vụ / nhà cung cấp / đăng nhập / API mở: lỗi lưu kèm mã (Đợt 2A) ---
  'project.cancelled': 'Bạn đã huỷ tạo video',
  'project.ffmpeg_interrupted': 'Việc dựng video bị ngắt giữa chừng, hãy bấm dựng lại',
  'project.compose_failed': 'Không dựng được video, vui lòng thử lại',
  'project.narration_audio_failed': 'Không tạo được giọng đọc cho cả video, vui lòng thử lại',
  'project.narration_audio_silent': 'Giọng đọc tạo ra gần như không có tiếng, hãy tạo lại giọng đọc',
  'project.narration_audio_bad_duration': 'Độ dài giọng đọc bất thường, hãy tạo lại giọng đọc',
  'project.storyboard_not_ready': 'Chưa có phân cảnh nên chưa làm tiếp được, hãy tạo kịch bản phân cảnh trước',
  'project.storyboard_empty': 'AI chưa trả về phân cảnh nào, vui lòng thử lại sau',
  'project.storyboard_invalid': 'AI trả về phân cảnh không đọc được, vui lòng thử lại',
  'tts.unavailable': 'Dịch vụ giọng đọc đang tạm thời không dùng được, vui lòng thử lại sau',
  'provider.network_error': 'Không kết nối được nhà cung cấp mô hình, vui lòng thử lại sau',
  'provider.timeout': 'Nhà cung cấp mô hình phản hồi quá lâu, vui lòng thử lại sau',
  'provider.failed': 'Nhà cung cấp mô hình chưa tạo được, vui lòng thử lại sau',
  'provider.content_rejected': 'Nội dung không qua được kiểm duyệt của nhà cung cấp mô hình, hãy sửa prompt hoặc ảnh tham chiếu rồi thử lại',
  'task.execution_failed': 'Không tạo được, vui lòng thử lại sau',
  'task.freeze_failed': 'Chưa tạm giữ được tiền cho lần tạo này, vui lòng thử lại sau',
  'task.handler_missing': 'Hệ thống chưa hỗ trợ việc này, hãy liên hệ với chúng tôi',
  'tool.ffmpeg_missing': 'Máy chủ đang thiếu công cụ ghép ảnh, hãy liên hệ với chúng tôi',
  'tool.collage_failed': 'Không ghép được ảnh, hãy thử ảnh khác',
  'auth.login_required': 'Vui lòng đăng nhập để tiếp tục',
  'auth.session_expired': 'Phiên đăng nhập đã hết hạn, vui lòng đăng nhập lại',
  'auth.api_key_missing': 'Thiếu API key',
  'auth.api_key_invalid': 'API key không hợp lệ hoặc đã bị thu hồi',
  'api.content_required': 'content không được để trống',
  'api.task_id_required': 'Thiếu task_id',
  'api.upstream_failed': 'Nhà cung cấp mô hình chưa tạo được, vui lòng thử lại sau',
  // --- Ngôn ngữ nội dung dự án (Việc P) ---
  'common.invalid_content_lang': 'Ngôn ngữ nội dung này chưa được hỗ trợ',
};

/**
 * Tra mã lỗi và điền tham số; mã chưa đăng ký trả chuỗi rỗng.
 * 参数 code：后端错误码；params：后端 params（*_fen 按展示货币格式化并去掉后缀）；formatFen：金额格式化（传 lib/currency 的 formatMoney）。
 */
export function translateErrorCode(
  code: string | null | undefined,
  params: unknown,
  formatFen: (fen: number) => string,
): string {
  if (!code) return "";
  const template = ADMIN_ERROR_MESSAGES[code];
  if (!template) return "";
  const vars: Record<string, string> = {};
  if (params && typeof params === "object") {
    for (const [key, value] of Object.entries(params as Record<string, unknown>)) {
      if (key.endsWith("_fen") && typeof value === "number") vars[key.slice(0, -4)] = formatFen(value);
      else if (typeof value === "string" || typeof value === "number") vars[key] = String(value);
    }
  }
  return template.replace(/\{(\w+)\}/g, (match, name: string) => vars[name] ?? match);
}
